{
 "title": "DetailsNODE",
 "description": "Basic host stats: CPU, Memory Usage, Disk Utilisation,  Filesystem usage and Predicted time to filesystems filling",
 "tags": [
  "ITALTEL",
  "prometheus",
  "VISIBLE"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   {
    "name": "myservice",
    "label": "Job",
    "query": "up{type=\"NODE\"}"
   },
   { "name": "instance", "label": "Node", "query": "up{job='$myservice'}" },
   { "name": "myjob", "label": "Jobname", "query": "${VAR_MYJOB}" },
   { "name": "fsThreshold", "label": "FIleSystemThreshold %", "query": "0,20,40,60,80" }
  ]
 },
 "panels": [
  {
   "title": "Node Monitoring Status",
   "type": "singlestat",
   "description": "OK if node is properly monitored, KO otherwise",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "up {job=\"$myservice\", instance=\"$instance\"}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Current CPU Usage",
   "type": "singlestat",
   "description": "Current CPU (Total) Usage (%)",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "1- avg without (cpu)(irate(node_cpu_seconds_total{job=\"$myservice\",instance=\"$instance\",mode=\"idle\"}[5m]))",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Current Memory Usage",
   "type": "singlestat",
   "description": "Current Memory (RAM) Usage (%)",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "100 * ( 1  -   ( (node_memory_MemFree_bytes{job='$myservice',instance='$instance'} + node_memory_Cached_bytes{job='$myservice',instance='$instance'} + node_memory_Buffers_bytes{job='$myservice',instance='$instance'} ) or node_memory_MemAvailable_bytes{job='$myservice',instance='$instance'}) / node_memory_MemTotal_bytes{ job='$myservice',instance='$instance'} )",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Most Used Filesystem",
   "type": "singlestat",
   "description": "Most used Filesystem (%)",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "max(1 - node_filesystem_avail_bytes{job='$myservice',instance='$instance',fstype!='rootfs',mountpoint!~'/(run).*'} / node_filesystem_size_bytes{job='$myservice',instance='$instance'} )",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "Time since last boot",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "node_time_seconds{job='$myservice',instance='$instance'}-node_boot_time_seconds{job='$myservice',instance='$instance'}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "CPU usage percentage",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=\"$myservice\",instance=\"$instance\",mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "1- avg without (cpu)(irate(node_cpu_seconds_total{job=\"$myservice\",instance=\"$instance\",mode=\"idle\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "RAM and Swap  usage in Gigabytes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{ job='$myservice',instance='$instance'} -   ( (node_memory_MemFree_bytes{job='$myservice',instance='$instance'} + node_memory_Cached_bytes{job='$myservice',instance='$instance'} + node_memory_Buffers_bytes{job='$myservice',instance='$instance'} ) or node_memory_MemAvailable_bytes{job='$myservice',instance='$instance'})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job='$myservice',instance='$instance'}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{job='$myservice',instance='$instance'}",
     "legendFormat": "Swap Total"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{job='$myservice',instance='$instance'} - node_memory_SwapFree_bytes{job='$myservice',instance='$instance'}",
     "legendFormat": "Swap Used"
    }
   ]
  },
  {
   "title": "Disk I/O Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{job='$myservice',instance='$instance',device!~'dm-.*'}[5m]) ",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "graph",
   "description": "File systems with usage percentage greater than the given threshold (currently $fsThreshold%)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - node_filesystem_avail_bytes{job='$myservice',instance='$instance',fstype!='rootfs',mountpoint!~'/(run).*'} / node_filesystem_size_bytes{job='$myservice',instance='$instance'}  > $fsThreshold/100",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network: byte received",
   "type": "graph",
   "description": "Byte rate RX for all inetwork nterfaces",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "(irate(node_network_receive_bytes_total{job='$myservice', instance='$instance',device != 'lo'}[5m]))",
     "legendFormat": "{{device}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network: byte transmitted",
   "type": "graph",
   "description": "Byte rate TX for all network interfaces",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "(irate(node_network_transmit_bytes_total{job='$myservice', instance='$instance',device != 'lo'}[5m]))",
     "legendFormat": "{{device}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}