{
 "title": "SummaryNODE",
 "description": "Overall System View",
 "tags": [
  "prometheus",
  "ITALTEL",
  "VISIBLE"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   {
    "name": "myMaxCpuInstance",
    "label": "myMaxCpuInstance",
    "query": "query_result(topk (1, (100 * (1 - avg by(instance)(rate(node_cpu_seconds_total{job='$myservice',mode='idle'}[5m]))))))"
   },
   {
    "name": "myMaxRamInstance",
    "label": "myMaxRamInstance",
    "query": "query_result( topk (1, (100* (1- avg by (instance) (((node_memory_MemFree_bytes{job='$myservice'} + node_memory_Cached_bytes{job='$myservice'} + node_memory_Buffers_bytes{job='$myservice'} ) or node_memory_MemAvailable_bytes{job='$myservice'})/node_memory_MemTotal_bytes{job='$myservice'})))) )"
   },
   {
    "name": "myMaxFSInstance",
    "label": "myMaxFSInstance",
    "query": "query_result( topk (1,  (1 - node_filesystem_free_bytes{job='$myservice',fstype!='rootfs',mountpoint!~'/(run).*'} / node_filesystem_size_bytes{job='$myservice'} )))"
   },
   {
    "name": "offlineNodes",
    "label": "offlineNodes",
    "query": "query_result( sum (up{job='$myservice'} == bool 0 ))"
   },
   {
    "name": "numOfNodes",
    "label": "numOfNodes",
    "query": "query_result( count (up{job='$myservice'} ))"
   },
   {
    "name": "myservice",
    "label": "Service",
    "query": "up{metricGroup=\"NODE\"}"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Max CPU Usage",
   "type": "singlestat",
   "description": "Max CPU usage (%) on the most cpu consuming node",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max ( (100 * (1 - avg by(instance)(rate(node_cpu_seconds_total{job='$myservice',mode='idle'}[5m])))))"
    }
   ]
  },
  {
   "title": "Max Memory Usage",
   "type": "singlestat",
   "description": "Max memory usage (%) on the most memory consuming node",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max((100* (1- avg by (instance) (((node_memory_MemFree_bytes{job='$myservice'} + node_memory_Cached_bytes{job='$myservice'} + node_memory_Buffers_bytes{job='$myservice'} ) or node_memory_MemAvailable_bytes{job='$myservice'})/node_memory_MemTotal_bytes{job='$myservice'}))))"
    }
   ]
  },
  {
   "title": "Max Filesystem Usage",
   "type": "singlestat",
   "description": "Max Filesystem usage (%) on the most disk consuming node",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 *  (max (1 - node_filesystem_free_bytes{job='$myservice',fstype!=\"rootfs\",mountpoint!~'/run.*'} / node_filesystem_size_bytes{job='$myservice'} ))"
    }
   ]
  },
  {
   "title": "Monitoring Health",
   "type": "singlestat",
   "description": "Are monitoring probes working correctly on all nodes?",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (up{job='$myservice'} == bool 0) == bool 0"
    }
   ]
  },
  { "title": "Monitoring Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Node Monitoring Status",
   "type": "grafana-piechart-panel",
   "description": "Is monitoring working correctly on all nodes?",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum(up{job='$myservice'}  == bool 1) ",
     "legendFormat": "up",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "sum (up{job='$myservice'} == bool 0)",
     "legendFormat": "down"
    }
   ]
  },
  {
   "title": "Monitoring Status",
   "type": "briangann-datatable-panel",
   "description": "0 (red) = not monitored\n1 (green) = monitored",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 5 },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "up {job='$myservice'}",
     "legendFormat": "{{instance}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Max CPU Usage",
   "type": "singlestat",
   "description": "Max CPU usage (%) on the most cpu consuming node",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "max ( (100 * (1 - avg by(instance)(rate(node_cpu_seconds_total{job='$myservice',mode='idle'}[5m])))))",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "100 * (1 - avg by(instance)(irate(node_cpu{job='p32v21u-fcapsdb3',mode='idle'}[5m])))",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top  CPU consuming nodes",
   "type": "briangann-datatable-panel",
   "description": "Max and Avg values are referred to dashboard time interval",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 15 },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": " ( (100 * (1 - avg by(instance)(rate(node_cpu_seconds_total{job='$myservice',mode='idle'}[5m])))))",
     "legendFormat": "{{instance}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Max Memory Usage",
   "type": "singlestat",
   "description": "Max memory usage (%) on the most memory consuming node",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 25 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "max((100* (1- avg by (instance) (((node_memory_MemFree_bytes{job='$myservice'} + node_memory_Cached_bytes{job='$myservice'} + node_memory_Buffers_bytes{job='$myservice'} ) or node_memory_MemAvailable_bytes{job='$myservice'})/node_memory_MemTotal_bytes{job='$myservice'}))))",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "100 * (1 - avg by(instance)(irate(node_cpu{job='p32v21u-fcapsdb3',mode='idle'}[5m])))",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Memory Consumimg Nodes",
   "type": "briangann-datatable-panel",
   "description": "Max and Avg values are referred to dashboard time interval",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 25 },
   "targets": [
    {
     "expr": "( (100* (1- avg by (instance) (((node_memory_MemFree_bytes{job='$myservice'} + node_memory_Cached_bytes{job='$myservice'} + node_memory_Buffers_bytes{job='$myservice'} ) or node_memory_MemAvailable_bytes{job='$myservice'})/node_memory_MemTotal_bytes{job='$myservice'}))))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "FIlesystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Max Filesystem Usage",
   "type": "singlestat",
   "description": "Max Filesystem usage (%) on the most disk consuming node",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 35 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "100 *  (max (1 - node_filesystem_free_bytes{job='$myservice',fstype!='rootfs',mountpoint!~'/(run).*'} / node_filesystem_size_bytes{job='$myservice'} ))",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "max (1 - node_filesystem_free{job='$myservice',fstype!='rootfs',mountpoint!~'/(run).*',mountpoint!=''} / node_filesystem_size{job='$myservice'} )",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Filesystem Consumimg Nodes",
   "type": "briangann-datatable-panel",
   "description": "Max and Avg values are referred to dashboard time interval",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 35 },
   "targets": [
    {
     "expr": "(100 *(1 - node_filesystem_free_bytes{job='$myservice',fstype!='rootfs',mountpoint!~'/(run).*',mountpoint!=''} / node_filesystem_size_bytes{job='$myservice'} ))",
     "legendFormat": "{{instance}} - {{mountpoint}}"
    }
   ]
  }
 ]
}