groups:
- name: 5GCity
  rules:
  
  - alert: InstanceDown
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Instance down (instance {{ $labels.instance }})"
      description: "Instance down\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

 # > 1%
  - alert: HighCpuLoad
    expr: 100 - ((rate(node_cpu_seconds_total{mode="idle"}[1m])) * 100) > 1
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "High CPU load (service {{ $labels.service }} , node {{ $labels.instance }})"
      description: "CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

# > 5%
  - alert: HighMemoryUsage
    expr: ((node_memory_MemTotal_bytes - node_memory_MemFree_bytes) / (node_memory_MemTotal_bytes )) * 100 > 5
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "High Memory Usage (service {{ $labels.service }} , node {{ $labels.instance }})"
      description: "Memory Usage is over 5% : current value {{ $value }}%"

# > 1kb/sec
  - alert: UnusualNetworkThroughputIn
    expr: (rate(node_network_receive_bytes_total[1m])) / 1024  > 1
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Unusual network throughput in (instance {{ $labels.instance }})"
      description: "Host network interfaces are probably receiving too much data (> 100 MB/s)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

