groups:
- name: 5GCity
  rules:
  
  - alert: InstanceDown
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Instance down (instance {{ $labels.instance }})"
      description: "Instance down\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
